language: go
dist: trusty

install:
    # Add Godeps dependencies to GOPATH and PATH
    - export GOPATH="${TRAVIS_BUILD_DIR}"
    - export PATH="$PATH:${TRAVIS_BUILD_DIR}/bin"
    - go get github.com/petelliott/pb

script:
    - go test github.com/petelliott/pb/lexer
    - go test github.com/petelliott/pb/parser
